title: IN[SCI]TE
name: IN[SCI]TE
email: reaal@inscite.co
baseurl: "/oxford" # the subpath of your site, e.g. /blog
url: "http://inscite.co" # the base hostname & protocol for your site
phase: 4 # the phase of the current year's event

# Navigation
nav:
  - name:           "committee"
    href:           "/committee"
  - name:           "sponsor"
    href:           "/sponsor"
  - name:           "talk"
    href:           "/talk"
  - name:           "attend 2017"
    href:           "/2017"
  - name:           "2016"
    href:           "/2016"
  - name:           "contact"
    href:           "/contact"
        

include: ['_pages']

# Build settings
markdown: kramdown
